spring:
  application:
    name: copygram_posts
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8828

posts:
  request-limit: 200

auth:
  base-url: http://localhost:8890
  path: /api/auth/validate

photos:
  base-url: http://localhost:8889
  path: /api/photos
