spring:
  application:
    name: copygram_posts
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/copygram_posts
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8828

posts:
  request-limit: 200

auth:
  base-url: http://localhost:8890
  path: /api/auth/validate

photos:
  base-url: http://localhost:8889
  path: /api/photos
